[package]
name = "hack_computer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hack_kernel = {path = "../hack_kernel"}
hack_tools = {path = "../hack_tools"}

minifb = "0.19.3"